### ISSUE TITLE
恢复的不明显

### ISSUE THREAD

**Issue by ccq1** [Reverier-Xu/IDA-Rizzo#1]
我准备了两个文件进行测试， file1: snake（有符号）， file2 : snake_s(去除符号版本)
我首先使用snake 制作了 .riz 文件
然后使用ida打开snake_s , 点击导入.riz 文件恢复符号，但是恢复的符号为0
![image](https://github.com/user-attachments/assets/26a8d8fc-0ae8-4cbe-805d-06d5de34d2d6)

我的操作方法为：
首先在snake文件中点击
![image](https://github.com/user-attachments/assets/7a7fb92d-af74-4784-88d2-64dab9655921)

然后在snake_s 文件中导入
![image](https://github.com/user-attachments/assets/f31edb67-63f6-4996-8089-91fe879935b1)

这是我的测试文件
[snake.zip](https://github.com/user-attachments/files/16560371/snake.zip)

**Comment by Reverier-Xu** [comment]
可以一并提供源代码和编译选项吗？Rizzo的效果比较玄学，我试一试

**Comment by ccq1** [comment]
感谢回复，这是snake程序源代码仓库https://github.com/gogakoreli/snake

**Comment by Reverier-Xu** [comment]
有些奇怪，我不管是自己编译测试，还是用你提供的附件测试，snake的rizzo恢复率都接近100%：

![image](https://github.com/user-attachments/assets/6199ba3b-853b-48f4-a4ac-94c041090e57)

![image](https://github.com/user-attachments/assets/ba72a9f6-31bc-4c68-b836-d09baf06b1ed)

**Comment by Reverier-Xu** [comment]
不过我好像看出来一点问题？

![image](https://github.com/user-attachments/assets/c529762b-7bfa-4e39-878f-96eacbb79dee)

你似乎不小心给strip版的二进制也做了一个rizzo文件，把原先的覆盖掉了
